### ISSUE TITLE
Access to KeypadLinc LEDs through PyISY / HA?

### ISSUE THREAD

**Issue by dethpickle** [automicus/PyISY#25]
Ryan or others,

I'm trying to use PyISY through Home Assistant to control KeypadLinc LEDs (other than the first button) remotely and am coming up short.  Is it possible to do at all?  Going through the PyISY docs I can't tell if I should be able to or not.

In the ISY944, the KPL 8's and 6's have all of the buttons show up as individually addressable and you can make scenes for the LED's and their brightness.  When jumping to HA, I could call those ISY scenes, but would like to directly turn a button's light on or off through the script.  I'm assuming it would be light.turn_on/off.  It works for the first button of each switch but none of the rest.

The idea I'm trying to satisfy is status reporting.  I want an HA automation where the LED indicates status of some other device.  That is, I'm turning the LED on and off without "pressing the button" or as ISY would say, having a Control event.  I'm thinking the failure I'm having is not an HA one - but I could be wrong.  I'm only thinking that because I can't see any reference to KPLs in the PyISY docs at all.

Here is a sample of what I'm trying.  In the following automation, the first pair assigned to the first button of a KPL 8 works.  The second pair gives: 

```
Jan 23 13:49:47 homeassistant hass[1881]: #033[32m17-01-23 13:49:47 INFO (Thread-10) [homeassistant.components.isy994] ISY Request: http://172.16.xxx.xxx:80/rest/nodes/40%20FC%2020%202/cmd/DOF#033[0m
Jan 23 13:49:47 homeassistant hass[1881]: #033[33m17-01-23 13:49:47 WARNING (Thread-10) [homeassistant.components.isy994] Bad ISY Request: http://172.16.xxx.xxx:80/rest/nodes/40%20FC%2020%202/cmd/DOF#033[0m
Jan 23 13:49:47 homeassistant hass[1881]: #033[33m17-01-23 13:49:47 WARNING (Thread-10) [homeassistant.components.isy994] ISY could not turn off node: 40 FC 20 2#033[0m
```

```yaml
- alias: Set Garage position indicators - open
  trigger:
    platform: state
    entity_id: cover.garage_door
  condition:
    condition: state
    entity_id: cover.garage_door
    state: 'open'
  action:
    service: light.turn_on
    entity_id: light.garage_door__master_8a
    data:
      brightness: 255

- alias: Set Garage position indicators - closed
  trigger:
    platform: state
    entity_id: cover.garage_door
  condition:
    condition: state
    entity_id: cover.garage_door
    state: 'closed'
  action:
    service: light.turn_off
    entity_id: light.garage_door__master_8a

- alias: Set Front Door indicators - unlocked
  trigger:
    platform: state
    entity_id: lock.zw_kwikset_front_door
  condition:
    condition: state
    entity_id: lock.zw_kwikset_front_door
    state: 'unlocked'
  action:
    service: light.turn_on
    entity_id: light.front_door__master_8b
    data:
      brightness: 255

- alias: Set Front Door indicators - locked
  trigger:
    platform: state
    entity_id: lock.zw_kwikset_front_door
  condition:
    condition: state
    entity_id: lock.zw_kwikset_front_door
    state: 'locked'
  action:
    service: light.turn_off
    entity_id: light.front_door__master_8b
```

Any knowledge if this style of direct access to the KPL LED states should be possible currently?  Or should I just switch over to setting up ISY scenes and activating them?  But if it is possible, then I can know I'm just doing it all wrong and have to figure it out.

Thanks!  And thanks for all the work over the years.
